// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TNT_ClassLib.DbAccess;

#nullable disable

namespace TNT_ClassLib.Migrations
{
    [DbContext(typeof(NoteDbContext))]
    [Migration("20220223233425_FindDb")]
    partial class FindDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("TNT_ClassLib.Models.NoteItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimePosted")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("NoteItems", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
